@startuml
skinparam classAttributeIconSize 0
skinparam monochrome true
hide circle

class Database {
  $connection
  __construct()
}

class Host {
  create(string $name, string $address): int
  read(int $id): array
  readByNameAddress(string $name, string $address): array
  readAll(): array
  readOrCreate(string $name, string $address): array
  update(int $id, string $name, string $address): int
  remove(int $id): int
}

Database -- Host
@enduml
