Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 9090, host: 9090
  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install -y cockpit
  SHELL
end