version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - .docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - php
      - mysql
    networks:
      - app-network

  mysql:
    container_name: mysql
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # volumes:
    #   - dbdata:/var/lib/mysql
    #   - .docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  php:
    container_name: php
    build: .
    image: php-pdo:7.3-fpm-alpine
    volumes:
      - ./src:/var/www
      # - .docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:9000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
# volumes:
#   dbdata:
#     driver: local
