# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.hostname = "lamp"
    config.vm.box = "ubuntu/bionic64"
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 3306, host: 3306
    config.vm.synced_folder "./src/", "/var/www/html/" #, mount_options: ["dmode=775,fmode=777"]
    config.vm.provider "virtualbox" do |vb|
      vb.name = "lamp"
    end
    config.vm.provision "shell", path: "install/lamp.sh"
end
