@startuml
skinparam classAttributeIconSize 0
skinparam monochrome true
hide circle

object Car
Car : numberOfDoors = 4
Car : howFast = 150
Car : power = 200

object Car2 
Car2 : numberOfDoors = 4
Car2 : howFast = 400
Car2 : power = 200

hide myCar members
hide myCar2 members

"myCar" --> Car
"myCar2" --> Car2
@enduml
