@startuml
skinparam classAttributeIconSize 0
skinparam monochrome true
hide circle

class Person {
    +name: String
    +__constructor(name: String)
    +hello(): String
}

class Student {
    +course: String
    +__constructor(name: String, course: String)
    +__toString(): String
    +hello(): String
}

Person <|-- Student
@enduml
