@startuml
skinparam classAttributeIconSize 0
skinparam monochrome true
hide circle

class Post {
    title: String
    text: String
    constructor(title: String, text: String)
    toHTML(): String
}
@enduml
