@startuml
skinparam classAttributeIconSize 0
skinparam monochrome true
hide circle

class Person {
    name: String
    constructor(name: String)
    hello(): String
}

class Student {
    id: String
    constructor(name: String, id: String)
}

Person <|-- Student
@enduml
