@startuml
skinparam classAttributeIconSize 0
skinparam monochrome true
hide circle

class Database {
  $connection
  __construct()
}

class NetInterface {
  create(string $name, string $ip, string $mask, string mac, int host_id): int
  read(int $id): array
  readByIp(string $ip): array
  readAll(): array
  readOrCreate(string $name, string $ip, string $mask, string mac, int host_id): array
  update(int $id, string $name, string $ip, string $mask, string mac, int host_id): int
  remove(int $id): int
}

Database -- NetInterface
@enduml
