# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # monitor
  config.vm.define "snmpserver" do |snmpserver|
    snmpserver.vm.hostname = "snmpserver"
    snmpserver.vm.box = "ubuntu/trusty64"
    snmpserver.vm.network "public_network"
    snmpserver.vm.network "forwarded_port", guest: 80, host: 8080
    snmpserver.vm.synced_folder ".", "/var/www/html"
    snmpserver.vm.provider "virtualbox" do |vb|
      vb.name = "snmpserver"
    end
    snmpserver.vm.provision "shell", path: "./install/snmpserver.sh"
  end

  # agent
  config.vm.define "snmpclient" do |snmpclient|
    snmpclient.vm.hostname = "snmpclient"
    snmpclient.vm.box = "ubuntu/trusty64"
    snmpclient.vm.network "public_network"
    snmpclient.vm.provider "virtualbox" do |vb|
      vb.name = "snmpclient"
    end
    snmpclient.vm.provision "shell", path: "./install/snmpclient.sh"
  end

end
